# DDR PS2 Controller
#
# Controller Component
#
# Kevin Cuzner

include ../common/common-top.mak

PROJECT=ddr-ps2-controller

all:: $(BINDIR)/$(PROJECT).bin $(BINDIR)/$(PROJECT).hex $(BINDIR)/$(BINARY).bin $(BINDIR)/$(BINARY).hex

include ../common/common-bot.mak

